export default {
    "1s": "1'ere",
    "2s": "2'ere",
    "3s": "3'ere",
    "4s": "4'ere",
    "5s": "5'ere",
    "6s": "6'ere",
    summary: "Sum",
    bonus: "Bonus",
    "1pair": "Et par",
    "2pairs": "To par",
    "3ofakind": "Tre ens",
    "4ofakind": "Fire ens",
    low: "Lav",
    high: "Høj",
    house: "Fuldt Hus",
    chance: "Chance",
    yatzy: "Yatzy",
    total: "I alt",
};
