export default {
    "1s": "Ones",
    "2s": "Twos",
    "3s": "Threes",
    "4s": "Fours",
    "5s": "Fives",
    "6s": "Sixes",
    summary: "Summary",
    bonus: "Bonus",
    "1pair": "One pair",
    "2pairs": "Two pairs",
    "3ofakind": "Three of a kind",
    "4ofakind": "Four of a kind",
    low: "Small straight",
    high: "Large straight",
    house: "Full house",
    chance: "Chance",
    yatzy: "Yatzy",
    total: "Total",
};
